name: Pull Request another repository

on:
  push:
    branches:
      - '*'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate test directory and file [optional]
        run: sh entrypoint.sh

      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.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 }}
        with:
          source_folder: 'theme'
          destination_repo: 'kgolovin/update_theme_action'
          destination_folder: 'theme'
          destination_branch: 'dev'
          user_email: 'koc.kit@gmail.com '
          user_name: 'kgolovin'