name: Push File

on:
  push:
      branches: [ main ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create pull request
        uses: ./.github/actions/sync-repo
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'test123'
          destination_repo: 'kgolovin/update_theme_action'
          destination_folder: 'test123'
          destination_base_branch: 'main'
          destination_head_branch: 'temp_dev_branch'
          user_email: 'koc.kit@gmail.com'
          user_name: 'kgolovin'
          pull_request_reviewers: 'reviewers'
