name: Sync Repositories

on: 
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'kgolovin/update_theme'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pushes to another repo
      uses: ./.github/actions/sync-repo
      env:
        API_TOKEN_GITHUB: ${{ secrets.update_theme }}
      with:
        source_folder: 'theme'
        destination_repo: 'kgolovin/update_theme_action'
        destination_folder: 'theme'
        user_email: 'konstantin.golovin@catenamedia.com'
        user_name: 'kgolovin'
        commit_msg: 'Check sync to another repo'
        destination_branch: main
